import { Job } from './types';

export const sampleJobs: Job[] = [
  {
    id: '1',
    company: 'Infosys UK',
    role: 'React Developer',
    location: 'London',
    salary: '£45,000 - £55,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: true,
    status: 'applied',
    deadline: '2025-05-01',
    source: 'LinkedIn',
    notes: 'Strong React + TypeScript requirement. Client is a fintech startup.',
    dateAdded: '2025-04-10',
    technology: 'React',
  },
  {
    id: '2',
    company: 'TCS (Tata Consultancy)',
    role: 'Java Full Stack Developer',
    location: 'Birmingham',
    salary: '£40,000 - £50,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: true,
    status: 'interview',
    deadline: '2025-04-25',
    source: 'Indeed',
    notes: 'Two rounds of interviews. Need Spring Boot experience.',
    dateAdded: '2025-04-08',
    technology: 'Java',
  },
  {
    id: '3',
    company: 'Wipro Digital',
    role: 'Python Data Engineer',
    location: 'Manchester',
    salary: '£50,000 - £65,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: true,
    status: 'saved',
    deadline: '2025-05-10',
    source: 'Gov.uk Sponsor List',
    notes: 'On the approved sponsor list. Python + AWS required.',
    dateAdded: '2025-04-12',
    technology: 'Python',
  },
  {
    id: '4',
    company: 'Capgemini UK',
    role: 'React Native Developer',
    location: 'London',
    salary: '£48,000 - £58,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: true,
    status: 'applied',
    deadline: '2025-04-30',
    source: 'Company Website',
    notes: 'Mobile app project for NHS client.',
    dateAdded: '2025-04-09',
    technology: 'React',
  },
  {
    id: '5',
    company: 'HCL Technologies',
    role: 'DevOps Engineer',
    location: 'Edinburgh',
    salary: '£42,000 - £52,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: false,
    status: 'saved',
    deadline: '2025-05-15',
    source: 'LinkedIn',
    notes: 'Need to confirm sponsorship. AWS + Kubernetes required.',
    dateAdded: '2025-04-11',
    technology: 'DevOps',
  },
  {
    id: '6',
    company: 'Cognizant',
    role: 'Angular Developer',
    location: 'Bristol',
    salary: '£38,000 - £48,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: true,
    status: 'offer',
    deadline: '2025-04-20',
    source: 'Indeed',
    notes: 'Offer received! Negotiating salary.',
    dateAdded: '2025-04-05',
    technology: 'Angular',
  },
  {
    id: '7',
    company: 'Accenture UK',
    role: 'Java Microservices Developer',
    location: 'London',
    salary: '£55,000 - £70,000',
    visaType: 'Skilled Worker',
    sponsorshipConfirmed: true,
    status: 'rejected',
    deadline: '2025-04-15',
    source: 'LinkedIn',
    notes: 'Rejected after technical round. Need more microservices experience.',
    dateAdded: '2025-04-03',
    technology: 'Java',
  },
  {
    id: '8',
    company: 'NHS Digital',
    role: 'React Frontend Developer',
    location: 'Leeds',
    salary: '£35,000 - £45,000',
    visaType: 'Health & Care',
    sponsorshipConfirmed: true,
    status: 'applied',
    deadline: '2025-05-05',
    source: 'Gov.uk',
    notes: 'Health & Care visa route. GDS standards required.',
    dateAdded: '2025-04-13',
    technology: 'React',
  },
];
